# Generated by Django 3.2.15 on 2022-08-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Date_of_Birth', models.DateField(max_length=10)),
                ('Blood_Group', models.CharField(max_length=5)),
                ('Contact_Number', models.CharField(max_length=10)),
                ('EMail', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=8)),
                ('Confirm_Password', models.CharField(max_length=8)),
            ],
        ),
    ]
