# Generated by Django 3.2.15 on 2022-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Date_of_Birth', models.CharField(max_length=10)),
                ('Contact_Number', models.CharField(max_length=10)),
                ('EMail', models.EmailField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('Speciality', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=8)),
                ('Confirm_Password', models.CharField(max_length=8)),
            ],
        ),
    ]
