# Generated by Django 3.2.15 on 2022-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Unique_ID',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
