# Generated by Django 3.2.15 on 2022-08-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_doctor_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Unique_ID',
        ),
        migrations.AddField(
            model_name='patient',
            name='Unique_ID',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
