# Generated by Django 3.2.15 on 2022-08-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220829_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Blood_Group',
            field=models.CharField(max_length=20),
        ),
    ]
