# Generated by Django 3.2.15 on 2022-08-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_patient_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='UniqueID',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
