# Generated by Django 3.2.15 on 2022-08-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_patient_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uniqueid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueID', models.CharField(max_length=100)),
            ],
        ),
    ]
