# Generated by Django 3.2.15 on 2022-11-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Date', models.CharField(max_length=10)),
                ('images', models.FileField(blank='true', upload_to='images')),
            ],
        ),
    ]
