# Generated by Django 3.2.15 on 2022-11-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
    ]
