# Generated by Django 3.2.15 on 2022-11-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_documents_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='images',
            new_name='Images',
        ),
        migrations.AlterField(
            model_name='document',
            name='Date',
            field=models.CharField(max_length=20),
        ),
    ]
