# Generated by Django 3.2.15 on 2022-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221118_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Images',
            field=models.FileField(blank='true', upload_to='user_<django.db.models.fields.CharField>/img'),
        ),
    ]
