# Generated by Django 3.2.15 on 2022-11-18 17:56

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_document_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Images',
            field=models.FileField(blank='true', upload_to=home.models.user_directory_path),
        ),
    ]
