# Generated by Django 3.2.15 on 2022-11-18 18:16

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20221118_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='DDate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='DName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Images',
        ),
        migrations.AlterField(
            model_name='document',
            name='Images',
            field=models.FileField(blank='true', upload_to=home.models.user_directory_path),
        ),
    ]
