# Generated by Django 3.2.15 on 2022-11-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20221118_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Uniqueid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
