# Generated by Django 3.2.15 on 2022-11-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_document_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='UniqueID',
            field=models.CharField(max_length=8),
        ),
    ]
