# Generated by Django 3.2.9 on 2022-11-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_patient_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='UniqueID',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
